### ISSUE TITLE
Can't create working TinyGo project!

### ISSUE THREAD

**Issue by galva99** [JetBrains/tinygo-plugin#5]
I downloaded the plugin in GoLand (latest version).
When attempting to create a TinyGo project, no SDK file was available in the dropdown, so I downloaded the latest version (0.19.0), however, it turns red. There are also no options available in the dropdown for target platform. I'm sure its likely due to something with my environment variables, but I'm really not sure. Uncharted waters for me here, I could really use some help. Thanks so much.

**Comment by galva99** [comment]
I can provide any pictures necessary to get this working.

**Comment by artspb** [comment]
I've copied your issue to the main tracker https://youtrack.jetbrains.com/issue/GO-11518 Let's continue there. Thanks!
